#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARCUS.Helpers
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbsca")]
	public partial class DALAVORAREDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPROD_VOLUMI_DA_LAVORARE(PROD_VOLUMI_DA_LAVORARE instance);
    partial void UpdatePROD_VOLUMI_DA_LAVORARE(PROD_VOLUMI_DA_LAVORARE instance);
    partial void DeletePROD_VOLUMI_DA_LAVORARE(PROD_VOLUMI_DA_LAVORARE instance);
    #endregion
		
		public DALAVORAREDataContext() : 
				base(global::MARCUS.Properties.Settings.Default.dbscaConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DALAVORAREDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DALAVORAREDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DALAVORAREDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DALAVORAREDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<PROD_VOLUMI_DA_LAVORARE> PROD_VOLUMI_DA_LAVORAREs
		{
			get
			{
				return this.GetTable<PROD_VOLUMI_DA_LAVORARE>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PROD_VOLUMI_DA_LAVORARE")]
	public partial class PROD_VOLUMI_DA_LAVORARE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _ID_DETTAGLIO_TIPO_LAVORAZIONE;
		
		private System.Nullable<int> _ID_OPERATORE;
		
		private System.Nullable<int> _ID_OPERATORE_IMPORT;
		
		private System.Nullable<System.DateTime> _DATA_IMPORT;
		
		private string _DETTAGLIO;
		
		private System.Nullable<System.DateTime> _DATA_BLOCCO;
		
		private System.Nullable<int> _N_STATO;
		
		private string _DATA_RIC_ACQ_DOC;
		
		private string _NOTE;
		
		private System.Nullable<long> _N_CONTENITORE;
		
		private System.Nullable<int> _PRIORITA;
		
		private System.Nullable<int> _ID_DETT_TIPO_LAV_PROVENIENZA;
		
		private System.Nullable<int> _ID_LAVORAZIONE_BOL;
		
		private string _NUMERO_CLIENTE;
		
		private System.Nullable<System.DateTime> _DATA_RIC_ACQ_DOC_DTIME;
		
		private int _ID_STATO_SOSPENSIONE;
		
		private System.Nullable<int> _ID_PROFILO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnID_DETTAGLIO_TIPO_LAVORAZIONEChanging(System.Nullable<int> value);
    partial void OnID_DETTAGLIO_TIPO_LAVORAZIONEChanged();
    partial void OnID_OPERATOREChanging(System.Nullable<int> value);
    partial void OnID_OPERATOREChanged();
    partial void OnID_OPERATORE_IMPORTChanging(System.Nullable<int> value);
    partial void OnID_OPERATORE_IMPORTChanged();
    partial void OnDATA_IMPORTChanging(System.Nullable<System.DateTime> value);
    partial void OnDATA_IMPORTChanged();
    partial void OnDETTAGLIOChanging(string value);
    partial void OnDETTAGLIOChanged();
    partial void OnDATA_BLOCCOChanging(System.Nullable<System.DateTime> value);
    partial void OnDATA_BLOCCOChanged();
    partial void OnN_STATOChanging(System.Nullable<int> value);
    partial void OnN_STATOChanged();
    partial void OnDATA_RIC_ACQ_DOCChanging(string value);
    partial void OnDATA_RIC_ACQ_DOCChanged();
    partial void OnNOTEChanging(string value);
    partial void OnNOTEChanged();
    partial void OnN_CONTENITOREChanging(System.Nullable<long> value);
    partial void OnN_CONTENITOREChanged();
    partial void OnPRIORITAChanging(System.Nullable<int> value);
    partial void OnPRIORITAChanged();
    partial void OnID_DETT_TIPO_LAV_PROVENIENZAChanging(System.Nullable<int> value);
    partial void OnID_DETT_TIPO_LAV_PROVENIENZAChanged();
    partial void OnID_LAVORAZIONE_BOLChanging(System.Nullable<int> value);
    partial void OnID_LAVORAZIONE_BOLChanged();
    partial void OnNUMERO_CLIENTEChanging(string value);
    partial void OnNUMERO_CLIENTEChanged();
    partial void OnDATA_RIC_ACQ_DOC_DTIMEChanging(System.Nullable<System.DateTime> value);
    partial void OnDATA_RIC_ACQ_DOC_DTIMEChanged();
    partial void OnID_STATO_SOSPENSIONEChanging(int value);
    partial void OnID_STATO_SOSPENSIONEChanged();
    partial void OnID_PROFILOChanging(System.Nullable<int> value);
    partial void OnID_PROFILOChanged();
    #endregion
		
		public PROD_VOLUMI_DA_LAVORARE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DETTAGLIO_TIPO_LAVORAZIONE", DbType="Int")]
		public System.Nullable<int> ID_DETTAGLIO_TIPO_LAVORAZIONE
		{
			get
			{
				return this._ID_DETTAGLIO_TIPO_LAVORAZIONE;
			}
			set
			{
				if ((this._ID_DETTAGLIO_TIPO_LAVORAZIONE != value))
				{
					this.OnID_DETTAGLIO_TIPO_LAVORAZIONEChanging(value);
					this.SendPropertyChanging();
					this._ID_DETTAGLIO_TIPO_LAVORAZIONE = value;
					this.SendPropertyChanged("ID_DETTAGLIO_TIPO_LAVORAZIONE");
					this.OnID_DETTAGLIO_TIPO_LAVORAZIONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_OPERATORE", DbType="Int")]
		public System.Nullable<int> ID_OPERATORE
		{
			get
			{
				return this._ID_OPERATORE;
			}
			set
			{
				if ((this._ID_OPERATORE != value))
				{
					this.OnID_OPERATOREChanging(value);
					this.SendPropertyChanging();
					this._ID_OPERATORE = value;
					this.SendPropertyChanged("ID_OPERATORE");
					this.OnID_OPERATOREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_OPERATORE_IMPORT", DbType="Int")]
		public System.Nullable<int> ID_OPERATORE_IMPORT
		{
			get
			{
				return this._ID_OPERATORE_IMPORT;
			}
			set
			{
				if ((this._ID_OPERATORE_IMPORT != value))
				{
					this.OnID_OPERATORE_IMPORTChanging(value);
					this.SendPropertyChanging();
					this._ID_OPERATORE_IMPORT = value;
					this.SendPropertyChanged("ID_OPERATORE_IMPORT");
					this.OnID_OPERATORE_IMPORTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATA_IMPORT", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATA_IMPORT
		{
			get
			{
				return this._DATA_IMPORT;
			}
			set
			{
				if ((this._DATA_IMPORT != value))
				{
					this.OnDATA_IMPORTChanging(value);
					this.SendPropertyChanging();
					this._DATA_IMPORT = value;
					this.SendPropertyChanged("DATA_IMPORT");
					this.OnDATA_IMPORTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DETTAGLIO", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DETTAGLIO
		{
			get
			{
				return this._DETTAGLIO;
			}
			set
			{
				if ((this._DETTAGLIO != value))
				{
					this.OnDETTAGLIOChanging(value);
					this.SendPropertyChanging();
					this._DETTAGLIO = value;
					this.SendPropertyChanged("DETTAGLIO");
					this.OnDETTAGLIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATA_BLOCCO", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATA_BLOCCO
		{
			get
			{
				return this._DATA_BLOCCO;
			}
			set
			{
				if ((this._DATA_BLOCCO != value))
				{
					this.OnDATA_BLOCCOChanging(value);
					this.SendPropertyChanging();
					this._DATA_BLOCCO = value;
					this.SendPropertyChanged("DATA_BLOCCO");
					this.OnDATA_BLOCCOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N_STATO", DbType="Int")]
		public System.Nullable<int> N_STATO
		{
			get
			{
				return this._N_STATO;
			}
			set
			{
				if ((this._N_STATO != value))
				{
					this.OnN_STATOChanging(value);
					this.SendPropertyChanging();
					this._N_STATO = value;
					this.SendPropertyChanged("N_STATO");
					this.OnN_STATOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATA_RIC_ACQ_DOC", DbType="NVarChar(255)")]
		public string DATA_RIC_ACQ_DOC
		{
			get
			{
				return this._DATA_RIC_ACQ_DOC;
			}
			set
			{
				if ((this._DATA_RIC_ACQ_DOC != value))
				{
					this.OnDATA_RIC_ACQ_DOCChanging(value);
					this.SendPropertyChanging();
					this._DATA_RIC_ACQ_DOC = value;
					this.SendPropertyChanged("DATA_RIC_ACQ_DOC");
					this.OnDATA_RIC_ACQ_DOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE", DbType="NVarChar(250)")]
		public string NOTE
		{
			get
			{
				return this._NOTE;
			}
			set
			{
				if ((this._NOTE != value))
				{
					this.OnNOTEChanging(value);
					this.SendPropertyChanging();
					this._NOTE = value;
					this.SendPropertyChanged("NOTE");
					this.OnNOTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N_CONTENITORE", DbType="BigInt")]
		public System.Nullable<long> N_CONTENITORE
		{
			get
			{
				return this._N_CONTENITORE;
			}
			set
			{
				if ((this._N_CONTENITORE != value))
				{
					this.OnN_CONTENITOREChanging(value);
					this.SendPropertyChanging();
					this._N_CONTENITORE = value;
					this.SendPropertyChanged("N_CONTENITORE");
					this.OnN_CONTENITOREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRIORITA", DbType="Int")]
		public System.Nullable<int> PRIORITA
		{
			get
			{
				return this._PRIORITA;
			}
			set
			{
				if ((this._PRIORITA != value))
				{
					this.OnPRIORITAChanging(value);
					this.SendPropertyChanging();
					this._PRIORITA = value;
					this.SendPropertyChanged("PRIORITA");
					this.OnPRIORITAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DETT_TIPO_LAV_PROVENIENZA", DbType="Int")]
		public System.Nullable<int> ID_DETT_TIPO_LAV_PROVENIENZA
		{
			get
			{
				return this._ID_DETT_TIPO_LAV_PROVENIENZA;
			}
			set
			{
				if ((this._ID_DETT_TIPO_LAV_PROVENIENZA != value))
				{
					this.OnID_DETT_TIPO_LAV_PROVENIENZAChanging(value);
					this.SendPropertyChanging();
					this._ID_DETT_TIPO_LAV_PROVENIENZA = value;
					this.SendPropertyChanged("ID_DETT_TIPO_LAV_PROVENIENZA");
					this.OnID_DETT_TIPO_LAV_PROVENIENZAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_LAVORAZIONE_BOL", DbType="Int")]
		public System.Nullable<int> ID_LAVORAZIONE_BOL
		{
			get
			{
				return this._ID_LAVORAZIONE_BOL;
			}
			set
			{
				if ((this._ID_LAVORAZIONE_BOL != value))
				{
					this.OnID_LAVORAZIONE_BOLChanging(value);
					this.SendPropertyChanging();
					this._ID_LAVORAZIONE_BOL = value;
					this.SendPropertyChanged("ID_LAVORAZIONE_BOL");
					this.OnID_LAVORAZIONE_BOLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUMERO_CLIENTE", DbType="NVarChar(255)")]
		public string NUMERO_CLIENTE
		{
			get
			{
				return this._NUMERO_CLIENTE;
			}
			set
			{
				if ((this._NUMERO_CLIENTE != value))
				{
					this.OnNUMERO_CLIENTEChanging(value);
					this.SendPropertyChanging();
					this._NUMERO_CLIENTE = value;
					this.SendPropertyChanged("NUMERO_CLIENTE");
					this.OnNUMERO_CLIENTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATA_RIC_ACQ_DOC_DTIME", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATA_RIC_ACQ_DOC_DTIME
		{
			get
			{
				return this._DATA_RIC_ACQ_DOC_DTIME;
			}
			set
			{
				if ((this._DATA_RIC_ACQ_DOC_DTIME != value))
				{
					this.OnDATA_RIC_ACQ_DOC_DTIMEChanging(value);
					this.SendPropertyChanging();
					this._DATA_RIC_ACQ_DOC_DTIME = value;
					this.SendPropertyChanged("DATA_RIC_ACQ_DOC_DTIME");
					this.OnDATA_RIC_ACQ_DOC_DTIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_STATO_SOSPENSIONE", DbType="Int NOT NULL")]
		public int ID_STATO_SOSPENSIONE
		{
			get
			{
				return this._ID_STATO_SOSPENSIONE;
			}
			set
			{
				if ((this._ID_STATO_SOSPENSIONE != value))
				{
					this.OnID_STATO_SOSPENSIONEChanging(value);
					this.SendPropertyChanging();
					this._ID_STATO_SOSPENSIONE = value;
					this.SendPropertyChanged("ID_STATO_SOSPENSIONE");
					this.OnID_STATO_SOSPENSIONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PROFILO", DbType="Int")]
		public System.Nullable<int> ID_PROFILO
		{
			get
			{
				return this._ID_PROFILO;
			}
			set
			{
				if ((this._ID_PROFILO != value))
				{
					this.OnID_PROFILOChanging(value);
					this.SendPropertyChanging();
					this._ID_PROFILO = value;
					this.SendPropertyChanged("ID_PROFILO");
					this.OnID_PROFILOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
