#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARCUS.Helpers
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BALTIK_DB")]
	public partial class EE62_ACQDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertACQ_ENEL_EE62(ACQ_ENEL_EE62 instance);
    partial void UpdateACQ_ENEL_EE62(ACQ_ENEL_EE62 instance);
    partial void DeleteACQ_ENEL_EE62(ACQ_ENEL_EE62 instance);
    #endregion
		
		public EE62_ACQDataContext() : 
				base(global::MARCUS.Properties.Settings.Default.BALTIK_DBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public EE62_ACQDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EE62_ACQDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EE62_ACQDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EE62_ACQDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ACQ_ENEL_EE62> ACQ_ENEL_EE62s
		{
			get
			{
				return this.GetTable<ACQ_ENEL_EE62>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ACQ_ENEL_EE62")]
	public partial class ACQ_ENEL_EE62 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _RIFERIMENTO;
		
		private string _NUMERO_CLIENTE;
		
		private string _DATA_ACQ_ENEL;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnRIFERIMENTOChanging(string value);
    partial void OnRIFERIMENTOChanged();
    partial void OnNUMERO_CLIENTEChanging(string value);
    partial void OnNUMERO_CLIENTEChanged();
    partial void OnDATA_ACQ_ENELChanging(string value);
    partial void OnDATA_ACQ_ENELChanged();
    #endregion
		
		public ACQ_ENEL_EE62()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RIFERIMENTO", DbType="NVarChar(50)")]
		public string RIFERIMENTO
		{
			get
			{
				return this._RIFERIMENTO;
			}
			set
			{
				if ((this._RIFERIMENTO != value))
				{
					this.OnRIFERIMENTOChanging(value);
					this.SendPropertyChanging();
					this._RIFERIMENTO = value;
					this.SendPropertyChanged("RIFERIMENTO");
					this.OnRIFERIMENTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUMERO_CLIENTE", DbType="NVarChar(50)")]
		public string NUMERO_CLIENTE
		{
			get
			{
				return this._NUMERO_CLIENTE;
			}
			set
			{
				if ((this._NUMERO_CLIENTE != value))
				{
					this.OnNUMERO_CLIENTEChanging(value);
					this.SendPropertyChanging();
					this._NUMERO_CLIENTE = value;
					this.SendPropertyChanged("NUMERO_CLIENTE");
					this.OnNUMERO_CLIENTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATA_ACQ_ENEL", DbType="NVarChar(50)")]
		public string DATA_ACQ_ENEL
		{
			get
			{
				return this._DATA_ACQ_ENEL;
			}
			set
			{
				if ((this._DATA_ACQ_ENEL != value))
				{
					this.OnDATA_ACQ_ENELChanging(value);
					this.SendPropertyChanging();
					this._DATA_ACQ_ENEL = value;
					this.SendPropertyChanged("DATA_ACQ_ENEL");
					this.OnDATA_ACQ_ENELChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
