#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARCUS.Helpers
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="baltikit_db")]
	public partial class FATJIKDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMARCUSP(MARCUSP instance);
    partial void UpdateMARCUSP(MARCUSP instance);
    partial void DeleteMARCUSP(MARCUSP instance);
    #endregion
		
		public FATJIKDataContext() : 
				base(global::MARCUS.Properties.Settings.Default.baltikit_dbConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public FATJIKDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}

        public FATJIKDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FATJIKDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FATJIKDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<MARCUSP> MARCUSPs
		{
			get
			{
				return this.GetTable<MARCUSP>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MARCUSP")]
	public partial class MARCUSP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _ID_PROD_VOLUMI_DA_LAVORARE;
		
		private System.Nullable<int> _ID_DETTAGLIO_TIPO_LAVORAZIONE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnID_PROD_VOLUMI_DA_LAVORAREChanging(System.Nullable<int> value);
    partial void OnID_PROD_VOLUMI_DA_LAVORAREChanged();
    partial void OnID_DETTAGLIO_TIPO_LAVORAZIONEChanging(System.Nullable<int> value);
    partial void OnID_DETTAGLIO_TIPO_LAVORAZIONEChanged();
    #endregion
		
		public MARCUSP()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PROD_VOLUMI_DA_LAVORARE", DbType="Int")]
		public System.Nullable<int> ID_PROD_VOLUMI_DA_LAVORARE
		{
			get
			{
				return this._ID_PROD_VOLUMI_DA_LAVORARE;
			}
			set
			{
				if ((this._ID_PROD_VOLUMI_DA_LAVORARE != value))
				{
					this.OnID_PROD_VOLUMI_DA_LAVORAREChanging(value);
					this.SendPropertyChanging();
					this._ID_PROD_VOLUMI_DA_LAVORARE = value;
					this.SendPropertyChanged("ID_PROD_VOLUMI_DA_LAVORARE");
					this.OnID_PROD_VOLUMI_DA_LAVORAREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DETTAGLIO_TIPO_LAVORAZIONE", DbType="Int")]
		public System.Nullable<int> ID_DETTAGLIO_TIPO_LAVORAZIONE
		{
			get
			{
				return this._ID_DETTAGLIO_TIPO_LAVORAZIONE;
			}
			set
			{
				if ((this._ID_DETTAGLIO_TIPO_LAVORAZIONE != value))
				{
					this.OnID_DETTAGLIO_TIPO_LAVORAZIONEChanging(value);
					this.SendPropertyChanging();
					this._ID_DETTAGLIO_TIPO_LAVORAZIONE = value;
					this.SendPropertyChanged("ID_DETTAGLIO_TIPO_LAVORAZIONE");
					this.OnID_DETTAGLIO_TIPO_LAVORAZIONEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
