#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARCUS.Helpers
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="baltikit_db")]
	public partial class KredenzialiDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_matricole(tbl_matricole instance);
    partial void Updatetbl_matricole(tbl_matricole instance);
    partial void Deletetbl_matricole(tbl_matricole instance);
    #endregion
		
		public KredenzialiDataContext() : 
				base(global::MARCUS.Properties.Settings.Default.baltikit_dbConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public KredenzialiDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KredenzialiDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KredenzialiDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KredenzialiDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_matricole> tbl_matricoles
		{
			get
			{
				return this.GetTable<tbl_matricole>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_matricole")]
	public partial class tbl_matricole : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _matricola;
		
		private string _password;
		
		private string _abilita;
		
		private string _name;
		
		private System.Nullable<bool> _avalible;
		
		private string _USER;
		
		private string _reparto;
		
		private string _psw_last_edit;
		
		private System.Nullable<int> _quantity_given;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnmatricolaChanging(string value);
    partial void OnmatricolaChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnabilitaChanging(string value);
    partial void OnabilitaChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnavalibleChanging(System.Nullable<bool> value);
    partial void OnavalibleChanged();
    partial void OnUSERChanging(string value);
    partial void OnUSERChanged();
    partial void OnrepartoChanging(string value);
    partial void OnrepartoChanged();
    partial void Onpsw_last_editChanging(string value);
    partial void Onpsw_last_editChanged();
    partial void Onquantity_givenChanging(System.Nullable<int> value);
    partial void Onquantity_givenChanged();
    #endregion
		
		public tbl_matricole()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matricola", DbType="NVarChar(10)")]
		public string matricola
		{
			get
			{
				return this._matricola;
			}
			set
			{
				if ((this._matricola != value))
				{
					this.OnmatricolaChanging(value);
					this.SendPropertyChanging();
					this._matricola = value;
					this.SendPropertyChanged("matricola");
					this.OnmatricolaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(50)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_abilita", DbType="NVarChar(50)")]
		public string abilita
		{
			get
			{
				return this._abilita;
			}
			set
			{
				if ((this._abilita != value))
				{
					this.OnabilitaChanging(value);
					this.SendPropertyChanging();
					this._abilita = value;
					this.SendPropertyChanged("abilita");
					this.OnabilitaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(150)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_avalible", DbType="Bit")]
		public System.Nullable<bool> avalible
		{
			get
			{
				return this._avalible;
			}
			set
			{
				if ((this._avalible != value))
				{
					this.OnavalibleChanging(value);
					this.SendPropertyChanging();
					this._avalible = value;
					this.SendPropertyChanged("avalible");
					this.OnavalibleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[USER]", Storage="_USER", DbType="NVarChar(10)")]
		public string USER
		{
			get
			{
				return this._USER;
			}
			set
			{
				if ((this._USER != value))
				{
					this.OnUSERChanging(value);
					this.SendPropertyChanging();
					this._USER = value;
					this.SendPropertyChanged("USER");
					this.OnUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reparto", DbType="NVarChar(50)")]
		public string reparto
		{
			get
			{
				return this._reparto;
			}
			set
			{
				if ((this._reparto != value))
				{
					this.OnrepartoChanging(value);
					this.SendPropertyChanging();
					this._reparto = value;
					this.SendPropertyChanged("reparto");
					this.OnrepartoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_psw_last_edit", DbType="NVarChar(20)")]
		public string psw_last_edit
		{
			get
			{
				return this._psw_last_edit;
			}
			set
			{
				if ((this._psw_last_edit != value))
				{
					this.Onpsw_last_editChanging(value);
					this.SendPropertyChanging();
					this._psw_last_edit = value;
					this.SendPropertyChanged("psw_last_edit");
					this.Onpsw_last_editChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity_given", DbType="Int")]
		public System.Nullable<int> quantity_given
		{
			get
			{
				return this._quantity_given;
			}
			set
			{
				if ((this._quantity_given != value))
				{
					this.Onquantity_givenChanging(value);
					this.SendPropertyChanging();
					this._quantity_given = value;
					this.SendPropertyChanged("quantity_given");
					this.Onquantity_givenChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
