#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARCUS.Helpers
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbsca")]
	public partial class LavarazioneDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertLAVORAZIONI_AGENTE(LAVORAZIONI_AGENTE instance);
    partial void UpdateLAVORAZIONI_AGENTE(LAVORAZIONI_AGENTE instance);
    partial void DeleteLAVORAZIONI_AGENTE(LAVORAZIONI_AGENTE instance);
    #endregion
		
		public LavarazioneDataContext() : 
				base(global::MARCUS.Properties.Settings.Default.dbscaConnectionString4, mappingSource)
		{
			OnCreated();
		}
		
		public LavarazioneDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LavarazioneDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LavarazioneDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LavarazioneDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<LAVORAZIONI_AGENTE> LAVORAZIONI_AGENTEs
		{
			get
			{
				return this.GetTable<LAVORAZIONI_AGENTE>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LAVORAZIONI_AGENTE")]
	public partial class LAVORAZIONI_AGENTE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _ID_RIFERIMENTO;
		
		private string _DATA_RICEZIONE_DOCUMENTO;
		
		private System.DateTime _DATA_LAVORAZIONE_DOCUMENTO;
		
		private System.Nullable<System.DateTime> _ORA_LAVORAZIONE_DOCUMENTO;
		
		private int _MATR_OPERATORE;
		
		private System.Nullable<int> _MATR_OPERATORE_WEB;
		
		private System.Nullable<int> _ID_TIPO_LAVORAZIONE;
		
		private System.Nullable<System.DateTime> _DATA_IMPORTAZIONE_DATI;
		
		private System.Nullable<int> _STAMPATO;
		
		private System.Nullable<System.DateTime> _DATA_STAMPA;
		
		private System.Nullable<long> _BLOCCO;
		
		private System.Nullable<int> _LAVORATO;
		
		private System.Nullable<int> _MATR_OPERATORE_STAMPA;
		
		private System.Nullable<int> _MATR_OPERATORE_INS_PRODUZIONE;
		
		private string _NUMERO_CLIENTE;
		
		private string _MOTIVO_RESO;
		
		private System.Nullable<int> _RESO_INVIATO;
		
		private string _PAGINA_DOCUMENTO;
		
		private string _FATTURA_DATA_DOCUMENTO;
		
		private System.Nullable<int> _ID_CODICE_RESO;
		
		private System.Nullable<System.DateTime> _DATA_INVIO_RESO;
		
		private System.Nullable<int> _MATR_OPERATORE_MAIL;
		
		private System.Nullable<int> _ESTRATTO;
		
		private System.Nullable<int> _ESAMINATI;
		
		private System.Nullable<int> _ESAMINATI_WEB;
		
		private System.Nullable<int> _ID_CONNESSIONE;
		
		private System.Nullable<int> _ID_ENTITA;
		
		private System.Nullable<System.DateTime> _START_DATE;
		
		private System.Nullable<System.DateTime> _END_DATE;
		
		private System.Nullable<int> _ID_DETTAGLIO_TIPO_LAVORAZIONE;
		
		private System.Nullable<char> _FORMAZIONE;
		
		private System.Nullable<char> _ESPORTATO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnID_RIFERIMENTOChanging(string value);
    partial void OnID_RIFERIMENTOChanged();
    partial void OnDATA_RICEZIONE_DOCUMENTOChanging(string value);
    partial void OnDATA_RICEZIONE_DOCUMENTOChanged();
    partial void OnDATA_LAVORAZIONE_DOCUMENTOChanging(System.DateTime value);
    partial void OnDATA_LAVORAZIONE_DOCUMENTOChanged();
    partial void OnORA_LAVORAZIONE_DOCUMENTOChanging(System.Nullable<System.DateTime> value);
    partial void OnORA_LAVORAZIONE_DOCUMENTOChanged();
    partial void OnMATR_OPERATOREChanging(int value);
    partial void OnMATR_OPERATOREChanged();
    partial void OnMATR_OPERATORE_WEBChanging(System.Nullable<int> value);
    partial void OnMATR_OPERATORE_WEBChanged();
    partial void OnID_TIPO_LAVORAZIONEChanging(System.Nullable<int> value);
    partial void OnID_TIPO_LAVORAZIONEChanged();
    partial void OnDATA_IMPORTAZIONE_DATIChanging(System.Nullable<System.DateTime> value);
    partial void OnDATA_IMPORTAZIONE_DATIChanged();
    partial void OnSTAMPATOChanging(System.Nullable<int> value);
    partial void OnSTAMPATOChanged();
    partial void OnDATA_STAMPAChanging(System.Nullable<System.DateTime> value);
    partial void OnDATA_STAMPAChanged();
    partial void OnBLOCCOChanging(System.Nullable<long> value);
    partial void OnBLOCCOChanged();
    partial void OnLAVORATOChanging(System.Nullable<int> value);
    partial void OnLAVORATOChanged();
    partial void OnMATR_OPERATORE_STAMPAChanging(System.Nullable<int> value);
    partial void OnMATR_OPERATORE_STAMPAChanged();
    partial void OnMATR_OPERATORE_INS_PRODUZIONEChanging(System.Nullable<int> value);
    partial void OnMATR_OPERATORE_INS_PRODUZIONEChanged();
    partial void OnNUMERO_CLIENTEChanging(string value);
    partial void OnNUMERO_CLIENTEChanged();
    partial void OnMOTIVO_RESOChanging(string value);
    partial void OnMOTIVO_RESOChanged();
    partial void OnRESO_INVIATOChanging(System.Nullable<int> value);
    partial void OnRESO_INVIATOChanged();
    partial void OnPAGINA_DOCUMENTOChanging(string value);
    partial void OnPAGINA_DOCUMENTOChanged();
    partial void OnFATTURA_DATA_DOCUMENTOChanging(string value);
    partial void OnFATTURA_DATA_DOCUMENTOChanged();
    partial void OnID_CODICE_RESOChanging(System.Nullable<int> value);
    partial void OnID_CODICE_RESOChanged();
    partial void OnDATA_INVIO_RESOChanging(System.Nullable<System.DateTime> value);
    partial void OnDATA_INVIO_RESOChanged();
    partial void OnMATR_OPERATORE_MAILChanging(System.Nullable<int> value);
    partial void OnMATR_OPERATORE_MAILChanged();
    partial void OnESTRATTOChanging(System.Nullable<int> value);
    partial void OnESTRATTOChanged();
    partial void OnESAMINATIChanging(System.Nullable<int> value);
    partial void OnESAMINATIChanged();
    partial void OnESAMINATI_WEBChanging(System.Nullable<int> value);
    partial void OnESAMINATI_WEBChanged();
    partial void OnID_CONNESSIONEChanging(System.Nullable<int> value);
    partial void OnID_CONNESSIONEChanged();
    partial void OnID_ENTITAChanging(System.Nullable<int> value);
    partial void OnID_ENTITAChanged();
    partial void OnSTART_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSTART_DATEChanged();
    partial void OnEND_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnEND_DATEChanged();
    partial void OnID_DETTAGLIO_TIPO_LAVORAZIONEChanging(System.Nullable<int> value);
    partial void OnID_DETTAGLIO_TIPO_LAVORAZIONEChanged();
    partial void OnFORMAZIONEChanging(System.Nullable<char> value);
    partial void OnFORMAZIONEChanged();
    partial void OnESPORTATOChanging(System.Nullable<char> value);
    partial void OnESPORTATOChanged();
    #endregion
		
		public LAVORAZIONI_AGENTE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_RIFERIMENTO", DbType="NChar(100)")]
		public string ID_RIFERIMENTO
		{
			get
			{
				return this._ID_RIFERIMENTO;
			}
			set
			{
				if ((this._ID_RIFERIMENTO != value))
				{
					this.OnID_RIFERIMENTOChanging(value);
					this.SendPropertyChanging();
					this._ID_RIFERIMENTO = value;
					this.SendPropertyChanged("ID_RIFERIMENTO");
					this.OnID_RIFERIMENTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATA_RICEZIONE_DOCUMENTO", DbType="NVarChar(50)")]
		public string DATA_RICEZIONE_DOCUMENTO
		{
			get
			{
				return this._DATA_RICEZIONE_DOCUMENTO;
			}
			set
			{
				if ((this._DATA_RICEZIONE_DOCUMENTO != value))
				{
					this.OnDATA_RICEZIONE_DOCUMENTOChanging(value);
					this.SendPropertyChanging();
					this._DATA_RICEZIONE_DOCUMENTO = value;
					this.SendPropertyChanged("DATA_RICEZIONE_DOCUMENTO");
					this.OnDATA_RICEZIONE_DOCUMENTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATA_LAVORAZIONE_DOCUMENTO", DbType="DateTime NOT NULL")]
		public System.DateTime DATA_LAVORAZIONE_DOCUMENTO
		{
			get
			{
				return this._DATA_LAVORAZIONE_DOCUMENTO;
			}
			set
			{
				if ((this._DATA_LAVORAZIONE_DOCUMENTO != value))
				{
					this.OnDATA_LAVORAZIONE_DOCUMENTOChanging(value);
					this.SendPropertyChanging();
					this._DATA_LAVORAZIONE_DOCUMENTO = value;
					this.SendPropertyChanged("DATA_LAVORAZIONE_DOCUMENTO");
					this.OnDATA_LAVORAZIONE_DOCUMENTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ORA_LAVORAZIONE_DOCUMENTO", DbType="DateTime")]
		public System.Nullable<System.DateTime> ORA_LAVORAZIONE_DOCUMENTO
		{
			get
			{
				return this._ORA_LAVORAZIONE_DOCUMENTO;
			}
			set
			{
				if ((this._ORA_LAVORAZIONE_DOCUMENTO != value))
				{
					this.OnORA_LAVORAZIONE_DOCUMENTOChanging(value);
					this.SendPropertyChanging();
					this._ORA_LAVORAZIONE_DOCUMENTO = value;
					this.SendPropertyChanged("ORA_LAVORAZIONE_DOCUMENTO");
					this.OnORA_LAVORAZIONE_DOCUMENTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATR_OPERATORE", DbType="Int NOT NULL")]
		public int MATR_OPERATORE
		{
			get
			{
				return this._MATR_OPERATORE;
			}
			set
			{
				if ((this._MATR_OPERATORE != value))
				{
					this.OnMATR_OPERATOREChanging(value);
					this.SendPropertyChanging();
					this._MATR_OPERATORE = value;
					this.SendPropertyChanged("MATR_OPERATORE");
					this.OnMATR_OPERATOREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATR_OPERATORE_WEB", DbType="Int")]
		public System.Nullable<int> MATR_OPERATORE_WEB
		{
			get
			{
				return this._MATR_OPERATORE_WEB;
			}
			set
			{
				if ((this._MATR_OPERATORE_WEB != value))
				{
					this.OnMATR_OPERATORE_WEBChanging(value);
					this.SendPropertyChanging();
					this._MATR_OPERATORE_WEB = value;
					this.SendPropertyChanged("MATR_OPERATORE_WEB");
					this.OnMATR_OPERATORE_WEBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TIPO_LAVORAZIONE", DbType="Int")]
		public System.Nullable<int> ID_TIPO_LAVORAZIONE
		{
			get
			{
				return this._ID_TIPO_LAVORAZIONE;
			}
			set
			{
				if ((this._ID_TIPO_LAVORAZIONE != value))
				{
					this.OnID_TIPO_LAVORAZIONEChanging(value);
					this.SendPropertyChanging();
					this._ID_TIPO_LAVORAZIONE = value;
					this.SendPropertyChanged("ID_TIPO_LAVORAZIONE");
					this.OnID_TIPO_LAVORAZIONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATA_IMPORTAZIONE_DATI", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATA_IMPORTAZIONE_DATI
		{
			get
			{
				return this._DATA_IMPORTAZIONE_DATI;
			}
			set
			{
				if ((this._DATA_IMPORTAZIONE_DATI != value))
				{
					this.OnDATA_IMPORTAZIONE_DATIChanging(value);
					this.SendPropertyChanging();
					this._DATA_IMPORTAZIONE_DATI = value;
					this.SendPropertyChanged("DATA_IMPORTAZIONE_DATI");
					this.OnDATA_IMPORTAZIONE_DATIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STAMPATO", DbType="Int")]
		public System.Nullable<int> STAMPATO
		{
			get
			{
				return this._STAMPATO;
			}
			set
			{
				if ((this._STAMPATO != value))
				{
					this.OnSTAMPATOChanging(value);
					this.SendPropertyChanging();
					this._STAMPATO = value;
					this.SendPropertyChanged("STAMPATO");
					this.OnSTAMPATOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATA_STAMPA", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATA_STAMPA
		{
			get
			{
				return this._DATA_STAMPA;
			}
			set
			{
				if ((this._DATA_STAMPA != value))
				{
					this.OnDATA_STAMPAChanging(value);
					this.SendPropertyChanging();
					this._DATA_STAMPA = value;
					this.SendPropertyChanged("DATA_STAMPA");
					this.OnDATA_STAMPAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BLOCCO", DbType="BigInt")]
		public System.Nullable<long> BLOCCO
		{
			get
			{
				return this._BLOCCO;
			}
			set
			{
				if ((this._BLOCCO != value))
				{
					this.OnBLOCCOChanging(value);
					this.SendPropertyChanging();
					this._BLOCCO = value;
					this.SendPropertyChanged("BLOCCO");
					this.OnBLOCCOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAVORATO", DbType="Int")]
		public System.Nullable<int> LAVORATO
		{
			get
			{
				return this._LAVORATO;
			}
			set
			{
				if ((this._LAVORATO != value))
				{
					this.OnLAVORATOChanging(value);
					this.SendPropertyChanging();
					this._LAVORATO = value;
					this.SendPropertyChanged("LAVORATO");
					this.OnLAVORATOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATR_OPERATORE_STAMPA", DbType="Int")]
		public System.Nullable<int> MATR_OPERATORE_STAMPA
		{
			get
			{
				return this._MATR_OPERATORE_STAMPA;
			}
			set
			{
				if ((this._MATR_OPERATORE_STAMPA != value))
				{
					this.OnMATR_OPERATORE_STAMPAChanging(value);
					this.SendPropertyChanging();
					this._MATR_OPERATORE_STAMPA = value;
					this.SendPropertyChanged("MATR_OPERATORE_STAMPA");
					this.OnMATR_OPERATORE_STAMPAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATR_OPERATORE_INS_PRODUZIONE", DbType="Int")]
		public System.Nullable<int> MATR_OPERATORE_INS_PRODUZIONE
		{
			get
			{
				return this._MATR_OPERATORE_INS_PRODUZIONE;
			}
			set
			{
				if ((this._MATR_OPERATORE_INS_PRODUZIONE != value))
				{
					this.OnMATR_OPERATORE_INS_PRODUZIONEChanging(value);
					this.SendPropertyChanging();
					this._MATR_OPERATORE_INS_PRODUZIONE = value;
					this.SendPropertyChanged("MATR_OPERATORE_INS_PRODUZIONE");
					this.OnMATR_OPERATORE_INS_PRODUZIONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUMERO_CLIENTE", DbType="NVarChar(255)")]
		public string NUMERO_CLIENTE
		{
			get
			{
				return this._NUMERO_CLIENTE;
			}
			set
			{
				if ((this._NUMERO_CLIENTE != value))
				{
					this.OnNUMERO_CLIENTEChanging(value);
					this.SendPropertyChanging();
					this._NUMERO_CLIENTE = value;
					this.SendPropertyChanged("NUMERO_CLIENTE");
					this.OnNUMERO_CLIENTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOTIVO_RESO", DbType="NVarChar(255)")]
		public string MOTIVO_RESO
		{
			get
			{
				return this._MOTIVO_RESO;
			}
			set
			{
				if ((this._MOTIVO_RESO != value))
				{
					this.OnMOTIVO_RESOChanging(value);
					this.SendPropertyChanging();
					this._MOTIVO_RESO = value;
					this.SendPropertyChanged("MOTIVO_RESO");
					this.OnMOTIVO_RESOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RESO_INVIATO", DbType="Int")]
		public System.Nullable<int> RESO_INVIATO
		{
			get
			{
				return this._RESO_INVIATO;
			}
			set
			{
				if ((this._RESO_INVIATO != value))
				{
					this.OnRESO_INVIATOChanging(value);
					this.SendPropertyChanging();
					this._RESO_INVIATO = value;
					this.SendPropertyChanged("RESO_INVIATO");
					this.OnRESO_INVIATOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAGINA_DOCUMENTO", DbType="NVarChar(50)")]
		public string PAGINA_DOCUMENTO
		{
			get
			{
				return this._PAGINA_DOCUMENTO;
			}
			set
			{
				if ((this._PAGINA_DOCUMENTO != value))
				{
					this.OnPAGINA_DOCUMENTOChanging(value);
					this.SendPropertyChanging();
					this._PAGINA_DOCUMENTO = value;
					this.SendPropertyChanged("PAGINA_DOCUMENTO");
					this.OnPAGINA_DOCUMENTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FATTURA_DATA_DOCUMENTO", DbType="NVarChar(50)")]
		public string FATTURA_DATA_DOCUMENTO
		{
			get
			{
				return this._FATTURA_DATA_DOCUMENTO;
			}
			set
			{
				if ((this._FATTURA_DATA_DOCUMENTO != value))
				{
					this.OnFATTURA_DATA_DOCUMENTOChanging(value);
					this.SendPropertyChanging();
					this._FATTURA_DATA_DOCUMENTO = value;
					this.SendPropertyChanged("FATTURA_DATA_DOCUMENTO");
					this.OnFATTURA_DATA_DOCUMENTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CODICE_RESO", DbType="Int")]
		public System.Nullable<int> ID_CODICE_RESO
		{
			get
			{
				return this._ID_CODICE_RESO;
			}
			set
			{
				if ((this._ID_CODICE_RESO != value))
				{
					this.OnID_CODICE_RESOChanging(value);
					this.SendPropertyChanging();
					this._ID_CODICE_RESO = value;
					this.SendPropertyChanged("ID_CODICE_RESO");
					this.OnID_CODICE_RESOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATA_INVIO_RESO", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATA_INVIO_RESO
		{
			get
			{
				return this._DATA_INVIO_RESO;
			}
			set
			{
				if ((this._DATA_INVIO_RESO != value))
				{
					this.OnDATA_INVIO_RESOChanging(value);
					this.SendPropertyChanging();
					this._DATA_INVIO_RESO = value;
					this.SendPropertyChanged("DATA_INVIO_RESO");
					this.OnDATA_INVIO_RESOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATR_OPERATORE_MAIL", DbType="Int")]
		public System.Nullable<int> MATR_OPERATORE_MAIL
		{
			get
			{
				return this._MATR_OPERATORE_MAIL;
			}
			set
			{
				if ((this._MATR_OPERATORE_MAIL != value))
				{
					this.OnMATR_OPERATORE_MAILChanging(value);
					this.SendPropertyChanging();
					this._MATR_OPERATORE_MAIL = value;
					this.SendPropertyChanged("MATR_OPERATORE_MAIL");
					this.OnMATR_OPERATORE_MAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTRATTO", DbType="Int")]
		public System.Nullable<int> ESTRATTO
		{
			get
			{
				return this._ESTRATTO;
			}
			set
			{
				if ((this._ESTRATTO != value))
				{
					this.OnESTRATTOChanging(value);
					this.SendPropertyChanging();
					this._ESTRATTO = value;
					this.SendPropertyChanged("ESTRATTO");
					this.OnESTRATTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESAMINATI", DbType="Int")]
		public System.Nullable<int> ESAMINATI
		{
			get
			{
				return this._ESAMINATI;
			}
			set
			{
				if ((this._ESAMINATI != value))
				{
					this.OnESAMINATIChanging(value);
					this.SendPropertyChanging();
					this._ESAMINATI = value;
					this.SendPropertyChanged("ESAMINATI");
					this.OnESAMINATIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESAMINATI_WEB", DbType="Int")]
		public System.Nullable<int> ESAMINATI_WEB
		{
			get
			{
				return this._ESAMINATI_WEB;
			}
			set
			{
				if ((this._ESAMINATI_WEB != value))
				{
					this.OnESAMINATI_WEBChanging(value);
					this.SendPropertyChanging();
					this._ESAMINATI_WEB = value;
					this.SendPropertyChanged("ESAMINATI_WEB");
					this.OnESAMINATI_WEBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CONNESSIONE", DbType="Int")]
		public System.Nullable<int> ID_CONNESSIONE
		{
			get
			{
				return this._ID_CONNESSIONE;
			}
			set
			{
				if ((this._ID_CONNESSIONE != value))
				{
					this.OnID_CONNESSIONEChanging(value);
					this.SendPropertyChanging();
					this._ID_CONNESSIONE = value;
					this.SendPropertyChanged("ID_CONNESSIONE");
					this.OnID_CONNESSIONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ENTITA", DbType="Int")]
		public System.Nullable<int> ID_ENTITA
		{
			get
			{
				return this._ID_ENTITA;
			}
			set
			{
				if ((this._ID_ENTITA != value))
				{
					this.OnID_ENTITAChanging(value);
					this.SendPropertyChanging();
					this._ID_ENTITA = value;
					this.SendPropertyChanged("ID_ENTITA");
					this.OnID_ENTITAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_START_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> START_DATE
		{
			get
			{
				return this._START_DATE;
			}
			set
			{
				if ((this._START_DATE != value))
				{
					this.OnSTART_DATEChanging(value);
					this.SendPropertyChanging();
					this._START_DATE = value;
					this.SendPropertyChanged("START_DATE");
					this.OnSTART_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_END_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> END_DATE
		{
			get
			{
				return this._END_DATE;
			}
			set
			{
				if ((this._END_DATE != value))
				{
					this.OnEND_DATEChanging(value);
					this.SendPropertyChanging();
					this._END_DATE = value;
					this.SendPropertyChanged("END_DATE");
					this.OnEND_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DETTAGLIO_TIPO_LAVORAZIONE", DbType="Int")]
		public System.Nullable<int> ID_DETTAGLIO_TIPO_LAVORAZIONE
		{
			get
			{
				return this._ID_DETTAGLIO_TIPO_LAVORAZIONE;
			}
			set
			{
				if ((this._ID_DETTAGLIO_TIPO_LAVORAZIONE != value))
				{
					this.OnID_DETTAGLIO_TIPO_LAVORAZIONEChanging(value);
					this.SendPropertyChanging();
					this._ID_DETTAGLIO_TIPO_LAVORAZIONE = value;
					this.SendPropertyChanged("ID_DETTAGLIO_TIPO_LAVORAZIONE");
					this.OnID_DETTAGLIO_TIPO_LAVORAZIONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FORMAZIONE", DbType="Char(1)")]
		public System.Nullable<char> FORMAZIONE
		{
			get
			{
				return this._FORMAZIONE;
			}
			set
			{
				if ((this._FORMAZIONE != value))
				{
					this.OnFORMAZIONEChanging(value);
					this.SendPropertyChanging();
					this._FORMAZIONE = value;
					this.SendPropertyChanged("FORMAZIONE");
					this.OnFORMAZIONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESPORTATO", DbType="Char(1)")]
		public System.Nullable<char> ESPORTATO
		{
			get
			{
				return this._ESPORTATO;
			}
			set
			{
				if ((this._ESPORTATO != value))
				{
					this.OnESPORTATOChanging(value);
					this.SendPropertyChanging();
					this._ESPORTATO = value;
					this.SendPropertyChanged("ESPORTATO");
					this.OnESPORTATOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
