#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARCUS.Helpers
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbsca")]
	public partial class USERDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertUSER(USER instance);
    partial void UpdateUSER(USER instance);
    partial void DeleteUSER(USER instance);
    #endregion
		
		public USERDataContext() : 
				base(global::MARCUS.Properties.Settings.Default.dbscaConnectionString3, mappingSource)
		{
			OnCreated();
		}
		
		public USERDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public USERDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public USERDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public USERDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<USER> USERs
		{
			get
			{
				return this.GetTable<USER>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[USER]")]
	public partial class USER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_USER;
		
		private string _USER_NAME;
		
		private string _COGNOME;
		
		private string _NOME;
		
		private string _PASSWORD;
		
		private System.Nullable<System.DateTime> _PASSWORD_DATE;
		
		private System.Nullable<int> _PASSWORD_SCADE;
		
		private System.Nullable<int> _STATUS;
		
		private System.DateTime _CREATION_DATE;
		
		private string _EMAIL;
		
		private string _ADDR1;
		
		private string _ADDR2;
		
		private string _CITTA;
		
		private string _PROVINCIA;
		
		private string _CAP;
		
		private string _TELEFONO;
		
		private string _FAX;
		
		private string _CELL;
		
		private System.Nullable<int> _TIPO_AUTENTICAZIONE;
		
		private System.Nullable<int> _MATRICOLA;
		
		private int _INTERFACCIA_ID;
		
		private string _MATR_ENEL;
		
		private string _BADGE;
		
		private string _FLAG_INTERINALE;
		
		private System.Nullable<int> _ID_SEDE;
		
		private System.Nullable<int> _ID_TURNO;
		
		private System.Nullable<int> _ID_AREA;
		
		private System.Nullable<System.DateTime> _DATA_INIZIO_VALIDITA;
		
		private System.Nullable<System.DateTime> _DATA_FINE_VALIDITA;
		
		private string _FLAG_VALIDITA;
		
		private string _PASSWORD_PROVVISORIA;
		
		private System.Nullable<System.DateTime> _SCADENZA_PASSWORD;
		
		private System.Nullable<int> _ID_REPARTO;
		
		private System.Nullable<int> _ID_GRUPPO_COLLEGAMENTI;
		
		private System.Nullable<int> _ID_CLIENTE;
		
		private string _CODICE_FISCALE;
		
		private System.Nullable<System.DateTime> _DATA_ABILITAZIONE_BADGE;
		
		private System.Nullable<System.DateTime> _DATA_DISABILITAZIONE_BADGE;
		
		private System.Nullable<int> _ID_SKILL;
		
		private System.Nullable<int> _ID_REPARTO_PRODUZIONE;
		
		private System.Nullable<int> _ID_DETTAGLIO_REPARTO_PRODUZIONE;
		
		private string _USER_SCANN;
		
		private System.Nullable<int> _ID_POSTAZIONE;
		
		private string _EMAIL_ALTERNATIVA;
		
		private System.Nullable<int> _MATRICOLA_MICRO_WIND;
		
		private System.Nullable<bool> _IS_SCADENZA_PASSWORD;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_USERChanging(int value);
    partial void OnID_USERChanged();
    partial void OnUSER_NAMEChanging(string value);
    partial void OnUSER_NAMEChanged();
    partial void OnCOGNOMEChanging(string value);
    partial void OnCOGNOMEChanged();
    partial void OnNOMEChanging(string value);
    partial void OnNOMEChanged();
    partial void OnPASSWORDChanging(string value);
    partial void OnPASSWORDChanged();
    partial void OnPASSWORD_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnPASSWORD_DATEChanged();
    partial void OnPASSWORD_SCADEChanging(System.Nullable<int> value);
    partial void OnPASSWORD_SCADEChanged();
    partial void OnSTATUSChanging(System.Nullable<int> value);
    partial void OnSTATUSChanged();
    partial void OnCREATION_DATEChanging(System.DateTime value);
    partial void OnCREATION_DATEChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnADDR1Changing(string value);
    partial void OnADDR1Changed();
    partial void OnADDR2Changing(string value);
    partial void OnADDR2Changed();
    partial void OnCITTAChanging(string value);
    partial void OnCITTAChanged();
    partial void OnPROVINCIAChanging(string value);
    partial void OnPROVINCIAChanged();
    partial void OnCAPChanging(string value);
    partial void OnCAPChanged();
    partial void OnTELEFONOChanging(string value);
    partial void OnTELEFONOChanged();
    partial void OnFAXChanging(string value);
    partial void OnFAXChanged();
    partial void OnCELLChanging(string value);
    partial void OnCELLChanged();
    partial void OnTIPO_AUTENTICAZIONEChanging(System.Nullable<int> value);
    partial void OnTIPO_AUTENTICAZIONEChanged();
    partial void OnMATRICOLAChanging(System.Nullable<int> value);
    partial void OnMATRICOLAChanged();
    partial void OnINTERFACCIA_IDChanging(int value);
    partial void OnINTERFACCIA_IDChanged();
    partial void OnMATR_ENELChanging(string value);
    partial void OnMATR_ENELChanged();
    partial void OnBADGEChanging(string value);
    partial void OnBADGEChanged();
    partial void OnFLAG_INTERINALEChanging(string value);
    partial void OnFLAG_INTERINALEChanged();
    partial void OnID_SEDEChanging(System.Nullable<int> value);
    partial void OnID_SEDEChanged();
    partial void OnID_TURNOChanging(System.Nullable<int> value);
    partial void OnID_TURNOChanged();
    partial void OnID_AREAChanging(System.Nullable<int> value);
    partial void OnID_AREAChanged();
    partial void OnDATA_INIZIO_VALIDITAChanging(System.Nullable<System.DateTime> value);
    partial void OnDATA_INIZIO_VALIDITAChanged();
    partial void OnDATA_FINE_VALIDITAChanging(System.Nullable<System.DateTime> value);
    partial void OnDATA_FINE_VALIDITAChanged();
    partial void OnFLAG_VALIDITAChanging(string value);
    partial void OnFLAG_VALIDITAChanged();
    partial void OnPASSWORD_PROVVISORIAChanging(string value);
    partial void OnPASSWORD_PROVVISORIAChanged();
    partial void OnSCADENZA_PASSWORDChanging(System.Nullable<System.DateTime> value);
    partial void OnSCADENZA_PASSWORDChanged();
    partial void OnID_REPARTOChanging(System.Nullable<int> value);
    partial void OnID_REPARTOChanged();
    partial void OnID_GRUPPO_COLLEGAMENTIChanging(System.Nullable<int> value);
    partial void OnID_GRUPPO_COLLEGAMENTIChanged();
    partial void OnID_CLIENTEChanging(System.Nullable<int> value);
    partial void OnID_CLIENTEChanged();
    partial void OnCODICE_FISCALEChanging(string value);
    partial void OnCODICE_FISCALEChanged();
    partial void OnDATA_ABILITAZIONE_BADGEChanging(System.Nullable<System.DateTime> value);
    partial void OnDATA_ABILITAZIONE_BADGEChanged();
    partial void OnDATA_DISABILITAZIONE_BADGEChanging(System.Nullable<System.DateTime> value);
    partial void OnDATA_DISABILITAZIONE_BADGEChanged();
    partial void OnID_SKILLChanging(System.Nullable<int> value);
    partial void OnID_SKILLChanged();
    partial void OnID_REPARTO_PRODUZIONEChanging(System.Nullable<int> value);
    partial void OnID_REPARTO_PRODUZIONEChanged();
    partial void OnID_DETTAGLIO_REPARTO_PRODUZIONEChanging(System.Nullable<int> value);
    partial void OnID_DETTAGLIO_REPARTO_PRODUZIONEChanged();
    partial void OnUSER_SCANNChanging(string value);
    partial void OnUSER_SCANNChanged();
    partial void OnID_POSTAZIONEChanging(System.Nullable<int> value);
    partial void OnID_POSTAZIONEChanged();
    partial void OnEMAIL_ALTERNATIVAChanging(string value);
    partial void OnEMAIL_ALTERNATIVAChanged();
    partial void OnMATRICOLA_MICRO_WINDChanging(System.Nullable<int> value);
    partial void OnMATRICOLA_MICRO_WINDChanged();
    partial void OnIS_SCADENZA_PASSWORDChanging(System.Nullable<bool> value);
    partial void OnIS_SCADENZA_PASSWORDChanged();
    #endregion
		
		public USER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USER", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_USER
		{
			get
			{
				return this._ID_USER;
			}
			set
			{
				if ((this._ID_USER != value))
				{
					this.OnID_USERChanging(value);
					this.SendPropertyChanging();
					this._ID_USER = value;
					this.SendPropertyChanged("ID_USER");
					this.OnID_USERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_NAME", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string USER_NAME
		{
			get
			{
				return this._USER_NAME;
			}
			set
			{
				if ((this._USER_NAME != value))
				{
					this.OnUSER_NAMEChanging(value);
					this.SendPropertyChanging();
					this._USER_NAME = value;
					this.SendPropertyChanged("USER_NAME");
					this.OnUSER_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COGNOME", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string COGNOME
		{
			get
			{
				return this._COGNOME;
			}
			set
			{
				if ((this._COGNOME != value))
				{
					this.OnCOGNOMEChanging(value);
					this.SendPropertyChanging();
					this._COGNOME = value;
					this.SendPropertyChanged("COGNOME");
					this.OnCOGNOMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOME", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NOME
		{
			get
			{
				return this._NOME;
			}
			set
			{
				if ((this._NOME != value))
				{
					this.OnNOMEChanging(value);
					this.SendPropertyChanging();
					this._NOME = value;
					this.SendPropertyChanged("NOME");
					this.OnNOMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PASSWORD
		{
			get
			{
				return this._PASSWORD;
			}
			set
			{
				if ((this._PASSWORD != value))
				{
					this.OnPASSWORDChanging(value);
					this.SendPropertyChanging();
					this._PASSWORD = value;
					this.SendPropertyChanged("PASSWORD");
					this.OnPASSWORDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> PASSWORD_DATE
		{
			get
			{
				return this._PASSWORD_DATE;
			}
			set
			{
				if ((this._PASSWORD_DATE != value))
				{
					this.OnPASSWORD_DATEChanging(value);
					this.SendPropertyChanging();
					this._PASSWORD_DATE = value;
					this.SendPropertyChanged("PASSWORD_DATE");
					this.OnPASSWORD_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD_SCADE", DbType="Int")]
		public System.Nullable<int> PASSWORD_SCADE
		{
			get
			{
				return this._PASSWORD_SCADE;
			}
			set
			{
				if ((this._PASSWORD_SCADE != value))
				{
					this.OnPASSWORD_SCADEChanging(value);
					this.SendPropertyChanging();
					this._PASSWORD_SCADE = value;
					this.SendPropertyChanged("PASSWORD_SCADE");
					this.OnPASSWORD_SCADEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="Int")]
		public System.Nullable<int> STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this.OnSTATUSChanging(value);
					this.SendPropertyChanging();
					this._STATUS = value;
					this.SendPropertyChanged("STATUS");
					this.OnSTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATION_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime CREATION_DATE
		{
			get
			{
				return this._CREATION_DATE;
			}
			set
			{
				if ((this._CREATION_DATE != value))
				{
					this.OnCREATION_DATEChanging(value);
					this.SendPropertyChanging();
					this._CREATION_DATE = value;
					this.SendPropertyChanged("CREATION_DATE");
					this.OnCREATION_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="VarChar(50)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDR1", DbType="VarChar(50)")]
		public string ADDR1
		{
			get
			{
				return this._ADDR1;
			}
			set
			{
				if ((this._ADDR1 != value))
				{
					this.OnADDR1Changing(value);
					this.SendPropertyChanging();
					this._ADDR1 = value;
					this.SendPropertyChanged("ADDR1");
					this.OnADDR1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDR2", DbType="VarChar(50)")]
		public string ADDR2
		{
			get
			{
				return this._ADDR2;
			}
			set
			{
				if ((this._ADDR2 != value))
				{
					this.OnADDR2Changing(value);
					this.SendPropertyChanging();
					this._ADDR2 = value;
					this.SendPropertyChanged("ADDR2");
					this.OnADDR2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CITTA", DbType="VarChar(80)")]
		public string CITTA
		{
			get
			{
				return this._CITTA;
			}
			set
			{
				if ((this._CITTA != value))
				{
					this.OnCITTAChanging(value);
					this.SendPropertyChanging();
					this._CITTA = value;
					this.SendPropertyChanged("CITTA");
					this.OnCITTAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROVINCIA", DbType="VarChar(20)")]
		public string PROVINCIA
		{
			get
			{
				return this._PROVINCIA;
			}
			set
			{
				if ((this._PROVINCIA != value))
				{
					this.OnPROVINCIAChanging(value);
					this.SendPropertyChanging();
					this._PROVINCIA = value;
					this.SendPropertyChanged("PROVINCIA");
					this.OnPROVINCIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAP", DbType="VarChar(20)")]
		public string CAP
		{
			get
			{
				return this._CAP;
			}
			set
			{
				if ((this._CAP != value))
				{
					this.OnCAPChanging(value);
					this.SendPropertyChanging();
					this._CAP = value;
					this.SendPropertyChanged("CAP");
					this.OnCAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFONO", DbType="VarChar(20)")]
		public string TELEFONO
		{
			get
			{
				return this._TELEFONO;
			}
			set
			{
				if ((this._TELEFONO != value))
				{
					this.OnTELEFONOChanging(value);
					this.SendPropertyChanging();
					this._TELEFONO = value;
					this.SendPropertyChanged("TELEFONO");
					this.OnTELEFONOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAX", DbType="VarChar(50)")]
		public string FAX
		{
			get
			{
				return this._FAX;
			}
			set
			{
				if ((this._FAX != value))
				{
					this.OnFAXChanging(value);
					this.SendPropertyChanging();
					this._FAX = value;
					this.SendPropertyChanged("FAX");
					this.OnFAXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CELL", DbType="VarChar(50)")]
		public string CELL
		{
			get
			{
				return this._CELL;
			}
			set
			{
				if ((this._CELL != value))
				{
					this.OnCELLChanging(value);
					this.SendPropertyChanging();
					this._CELL = value;
					this.SendPropertyChanged("CELL");
					this.OnCELLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIPO_AUTENTICAZIONE", DbType="Int")]
		public System.Nullable<int> TIPO_AUTENTICAZIONE
		{
			get
			{
				return this._TIPO_AUTENTICAZIONE;
			}
			set
			{
				if ((this._TIPO_AUTENTICAZIONE != value))
				{
					this.OnTIPO_AUTENTICAZIONEChanging(value);
					this.SendPropertyChanging();
					this._TIPO_AUTENTICAZIONE = value;
					this.SendPropertyChanged("TIPO_AUTENTICAZIONE");
					this.OnTIPO_AUTENTICAZIONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATRICOLA", DbType="Int")]
		public System.Nullable<int> MATRICOLA
		{
			get
			{
				return this._MATRICOLA;
			}
			set
			{
				if ((this._MATRICOLA != value))
				{
					this.OnMATRICOLAChanging(value);
					this.SendPropertyChanging();
					this._MATRICOLA = value;
					this.SendPropertyChanged("MATRICOLA");
					this.OnMATRICOLAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INTERFACCIA_ID", DbType="Int NOT NULL")]
		public int INTERFACCIA_ID
		{
			get
			{
				return this._INTERFACCIA_ID;
			}
			set
			{
				if ((this._INTERFACCIA_ID != value))
				{
					this.OnINTERFACCIA_IDChanging(value);
					this.SendPropertyChanging();
					this._INTERFACCIA_ID = value;
					this.SendPropertyChanged("INTERFACCIA_ID");
					this.OnINTERFACCIA_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATR_ENEL", DbType="NVarChar(50)")]
		public string MATR_ENEL
		{
			get
			{
				return this._MATR_ENEL;
			}
			set
			{
				if ((this._MATR_ENEL != value))
				{
					this.OnMATR_ENELChanging(value);
					this.SendPropertyChanging();
					this._MATR_ENEL = value;
					this.SendPropertyChanged("MATR_ENEL");
					this.OnMATR_ENELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BADGE", DbType="NVarChar(255)")]
		public string BADGE
		{
			get
			{
				return this._BADGE;
			}
			set
			{
				if ((this._BADGE != value))
				{
					this.OnBADGEChanging(value);
					this.SendPropertyChanging();
					this._BADGE = value;
					this.SendPropertyChanged("BADGE");
					this.OnBADGEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLAG_INTERINALE", DbType="NVarChar(255)")]
		public string FLAG_INTERINALE
		{
			get
			{
				return this._FLAG_INTERINALE;
			}
			set
			{
				if ((this._FLAG_INTERINALE != value))
				{
					this.OnFLAG_INTERINALEChanging(value);
					this.SendPropertyChanging();
					this._FLAG_INTERINALE = value;
					this.SendPropertyChanged("FLAG_INTERINALE");
					this.OnFLAG_INTERINALEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_SEDE", DbType="Int")]
		public System.Nullable<int> ID_SEDE
		{
			get
			{
				return this._ID_SEDE;
			}
			set
			{
				if ((this._ID_SEDE != value))
				{
					this.OnID_SEDEChanging(value);
					this.SendPropertyChanging();
					this._ID_SEDE = value;
					this.SendPropertyChanged("ID_SEDE");
					this.OnID_SEDEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TURNO", DbType="Int")]
		public System.Nullable<int> ID_TURNO
		{
			get
			{
				return this._ID_TURNO;
			}
			set
			{
				if ((this._ID_TURNO != value))
				{
					this.OnID_TURNOChanging(value);
					this.SendPropertyChanging();
					this._ID_TURNO = value;
					this.SendPropertyChanged("ID_TURNO");
					this.OnID_TURNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_AREA", DbType="Int")]
		public System.Nullable<int> ID_AREA
		{
			get
			{
				return this._ID_AREA;
			}
			set
			{
				if ((this._ID_AREA != value))
				{
					this.OnID_AREAChanging(value);
					this.SendPropertyChanging();
					this._ID_AREA = value;
					this.SendPropertyChanged("ID_AREA");
					this.OnID_AREAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATA_INIZIO_VALIDITA", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATA_INIZIO_VALIDITA
		{
			get
			{
				return this._DATA_INIZIO_VALIDITA;
			}
			set
			{
				if ((this._DATA_INIZIO_VALIDITA != value))
				{
					this.OnDATA_INIZIO_VALIDITAChanging(value);
					this.SendPropertyChanging();
					this._DATA_INIZIO_VALIDITA = value;
					this.SendPropertyChanged("DATA_INIZIO_VALIDITA");
					this.OnDATA_INIZIO_VALIDITAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATA_FINE_VALIDITA", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATA_FINE_VALIDITA
		{
			get
			{
				return this._DATA_FINE_VALIDITA;
			}
			set
			{
				if ((this._DATA_FINE_VALIDITA != value))
				{
					this.OnDATA_FINE_VALIDITAChanging(value);
					this.SendPropertyChanging();
					this._DATA_FINE_VALIDITA = value;
					this.SendPropertyChanged("DATA_FINE_VALIDITA");
					this.OnDATA_FINE_VALIDITAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLAG_VALIDITA", DbType="NVarChar(1)")]
		public string FLAG_VALIDITA
		{
			get
			{
				return this._FLAG_VALIDITA;
			}
			set
			{
				if ((this._FLAG_VALIDITA != value))
				{
					this.OnFLAG_VALIDITAChanging(value);
					this.SendPropertyChanging();
					this._FLAG_VALIDITA = value;
					this.SendPropertyChanged("FLAG_VALIDITA");
					this.OnFLAG_VALIDITAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD_PROVVISORIA", DbType="NVarChar(50)")]
		public string PASSWORD_PROVVISORIA
		{
			get
			{
				return this._PASSWORD_PROVVISORIA;
			}
			set
			{
				if ((this._PASSWORD_PROVVISORIA != value))
				{
					this.OnPASSWORD_PROVVISORIAChanging(value);
					this.SendPropertyChanging();
					this._PASSWORD_PROVVISORIA = value;
					this.SendPropertyChanged("PASSWORD_PROVVISORIA");
					this.OnPASSWORD_PROVVISORIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCADENZA_PASSWORD", DbType="DateTime")]
		public System.Nullable<System.DateTime> SCADENZA_PASSWORD
		{
			get
			{
				return this._SCADENZA_PASSWORD;
			}
			set
			{
				if ((this._SCADENZA_PASSWORD != value))
				{
					this.OnSCADENZA_PASSWORDChanging(value);
					this.SendPropertyChanging();
					this._SCADENZA_PASSWORD = value;
					this.SendPropertyChanged("SCADENZA_PASSWORD");
					this.OnSCADENZA_PASSWORDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_REPARTO", DbType="Int")]
		public System.Nullable<int> ID_REPARTO
		{
			get
			{
				return this._ID_REPARTO;
			}
			set
			{
				if ((this._ID_REPARTO != value))
				{
					this.OnID_REPARTOChanging(value);
					this.SendPropertyChanging();
					this._ID_REPARTO = value;
					this.SendPropertyChanged("ID_REPARTO");
					this.OnID_REPARTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_GRUPPO_COLLEGAMENTI", DbType="Int")]
		public System.Nullable<int> ID_GRUPPO_COLLEGAMENTI
		{
			get
			{
				return this._ID_GRUPPO_COLLEGAMENTI;
			}
			set
			{
				if ((this._ID_GRUPPO_COLLEGAMENTI != value))
				{
					this.OnID_GRUPPO_COLLEGAMENTIChanging(value);
					this.SendPropertyChanging();
					this._ID_GRUPPO_COLLEGAMENTI = value;
					this.SendPropertyChanged("ID_GRUPPO_COLLEGAMENTI");
					this.OnID_GRUPPO_COLLEGAMENTIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CLIENTE", DbType="Int")]
		public System.Nullable<int> ID_CLIENTE
		{
			get
			{
				return this._ID_CLIENTE;
			}
			set
			{
				if ((this._ID_CLIENTE != value))
				{
					this.OnID_CLIENTEChanging(value);
					this.SendPropertyChanging();
					this._ID_CLIENTE = value;
					this.SendPropertyChanged("ID_CLIENTE");
					this.OnID_CLIENTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODICE_FISCALE", DbType="NVarChar(50)")]
		public string CODICE_FISCALE
		{
			get
			{
				return this._CODICE_FISCALE;
			}
			set
			{
				if ((this._CODICE_FISCALE != value))
				{
					this.OnCODICE_FISCALEChanging(value);
					this.SendPropertyChanging();
					this._CODICE_FISCALE = value;
					this.SendPropertyChanged("CODICE_FISCALE");
					this.OnCODICE_FISCALEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATA_ABILITAZIONE_BADGE", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATA_ABILITAZIONE_BADGE
		{
			get
			{
				return this._DATA_ABILITAZIONE_BADGE;
			}
			set
			{
				if ((this._DATA_ABILITAZIONE_BADGE != value))
				{
					this.OnDATA_ABILITAZIONE_BADGEChanging(value);
					this.SendPropertyChanging();
					this._DATA_ABILITAZIONE_BADGE = value;
					this.SendPropertyChanged("DATA_ABILITAZIONE_BADGE");
					this.OnDATA_ABILITAZIONE_BADGEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATA_DISABILITAZIONE_BADGE", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATA_DISABILITAZIONE_BADGE
		{
			get
			{
				return this._DATA_DISABILITAZIONE_BADGE;
			}
			set
			{
				if ((this._DATA_DISABILITAZIONE_BADGE != value))
				{
					this.OnDATA_DISABILITAZIONE_BADGEChanging(value);
					this.SendPropertyChanging();
					this._DATA_DISABILITAZIONE_BADGE = value;
					this.SendPropertyChanged("DATA_DISABILITAZIONE_BADGE");
					this.OnDATA_DISABILITAZIONE_BADGEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_SKILL", DbType="Int")]
		public System.Nullable<int> ID_SKILL
		{
			get
			{
				return this._ID_SKILL;
			}
			set
			{
				if ((this._ID_SKILL != value))
				{
					this.OnID_SKILLChanging(value);
					this.SendPropertyChanging();
					this._ID_SKILL = value;
					this.SendPropertyChanged("ID_SKILL");
					this.OnID_SKILLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_REPARTO_PRODUZIONE", DbType="Int")]
		public System.Nullable<int> ID_REPARTO_PRODUZIONE
		{
			get
			{
				return this._ID_REPARTO_PRODUZIONE;
			}
			set
			{
				if ((this._ID_REPARTO_PRODUZIONE != value))
				{
					this.OnID_REPARTO_PRODUZIONEChanging(value);
					this.SendPropertyChanging();
					this._ID_REPARTO_PRODUZIONE = value;
					this.SendPropertyChanged("ID_REPARTO_PRODUZIONE");
					this.OnID_REPARTO_PRODUZIONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DETTAGLIO_REPARTO_PRODUZIONE", DbType="Int")]
		public System.Nullable<int> ID_DETTAGLIO_REPARTO_PRODUZIONE
		{
			get
			{
				return this._ID_DETTAGLIO_REPARTO_PRODUZIONE;
			}
			set
			{
				if ((this._ID_DETTAGLIO_REPARTO_PRODUZIONE != value))
				{
					this.OnID_DETTAGLIO_REPARTO_PRODUZIONEChanging(value);
					this.SendPropertyChanging();
					this._ID_DETTAGLIO_REPARTO_PRODUZIONE = value;
					this.SendPropertyChanged("ID_DETTAGLIO_REPARTO_PRODUZIONE");
					this.OnID_DETTAGLIO_REPARTO_PRODUZIONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_SCANN", DbType="NVarChar(1)")]
		public string USER_SCANN
		{
			get
			{
				return this._USER_SCANN;
			}
			set
			{
				if ((this._USER_SCANN != value))
				{
					this.OnUSER_SCANNChanging(value);
					this.SendPropertyChanging();
					this._USER_SCANN = value;
					this.SendPropertyChanged("USER_SCANN");
					this.OnUSER_SCANNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_POSTAZIONE", DbType="Int")]
		public System.Nullable<int> ID_POSTAZIONE
		{
			get
			{
				return this._ID_POSTAZIONE;
			}
			set
			{
				if ((this._ID_POSTAZIONE != value))
				{
					this.OnID_POSTAZIONEChanging(value);
					this.SendPropertyChanging();
					this._ID_POSTAZIONE = value;
					this.SendPropertyChanged("ID_POSTAZIONE");
					this.OnID_POSTAZIONEChanged();
				}
			}
		}
		
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL_ALTERNATIVA", DbType="NVarChar(50)")]
		public string EMAIL_ALTERNATIVA
		{
			get
			{
				return this._EMAIL_ALTERNATIVA;
			}
			set
			{
				if ((this._EMAIL_ALTERNATIVA != value))
				{
					this.OnEMAIL_ALTERNATIVAChanging(value);
					this.SendPropertyChanging();
					this._EMAIL_ALTERNATIVA = value;
					this.SendPropertyChanged("EMAIL_ALTERNATIVA");
					this.OnEMAIL_ALTERNATIVAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATRICOLA_MICRO_WIND", DbType="Int")]
		public System.Nullable<int> MATRICOLA_MICRO_WIND
		{
			get
			{
				return this._MATRICOLA_MICRO_WIND;
			}
			set
			{
				if ((this._MATRICOLA_MICRO_WIND != value))
				{
					this.OnMATRICOLA_MICRO_WINDChanging(value);
					this.SendPropertyChanging();
					this._MATRICOLA_MICRO_WIND = value;
					this.SendPropertyChanged("MATRICOLA_MICRO_WIND");
					this.OnMATRICOLA_MICRO_WINDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IS_SCADENZA_PASSWORD", DbType="Bit")]
		public System.Nullable<bool> IS_SCADENZA_PASSWORD
		{
			get
			{
				return this._IS_SCADENZA_PASSWORD;
			}
			set
			{
				if ((this._IS_SCADENZA_PASSWORD != value))
				{
					this.OnIS_SCADENZA_PASSWORDChanging(value);
					this.SendPropertyChanging();
					this._IS_SCADENZA_PASSWORD = value;
					this.SendPropertyChanged("IS_SCADENZA_PASSWORD");
					this.OnIS_SCADENZA_PASSWORDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
